#アクション名
name: Terraform Run（Composite）
#説明文
description: OIDC + SOPS 復号 + init の共通化
#外部から与えられるパラメータ
inputs:
  stack: { required: true }
  role_arn: { required: true }
  region: { required: true }
runs:
  using: "composite"
  steps:
    #GitHub Actions の OIDC 機能を使って、Secrets に直接 AWS Key を保存せずに AWS にアクセスできるようにしている。
    - uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ inputs.role_arn }}
        aws-region: ${{ inputs.region }}
    - shell: bash
      run: |
        echo "${{ secrets.SOPS_AGE_KEY }}" > /tmp/agekey.txt
        export SOPS_AGE_KEY_FILE=/tmp/agekey.txt
        if [ -f "${{ inputs.stack }}/secrets.enc.tfvars" ]; then
          sops -d "${{ inputs.stack }}/secrets.enc.tfvars" > "${{ inputs.stack }}/secrets.dec.tfvars"
        fi
        terraform -chdir=${{ inputs.stack }} init -backend-config=${{ inputs.stack }}/backend.hcl
