CREATE ROLE IF NOT EXISTS SYSADMIN_READONLY COMMENT='基盤参照専用';
CREATE ROLE IF NOT EXISTS APP_ADMIN COMMENT='アプリ管理者';
CREATE ROLE IF NOT EXISTS APP_USER COMMENT='アプリ一般ユーザ';
GRANT ROLE SYSADMIN_READONLY TO ROLE SECURITYADMIN;
GRANT ROLE SYSADMIN_READONLY TO ROLE SYSADMIN;
GRANT ROLE APP_ADMIN TO ROLE SYSADMIN_READONLY;
GRANT ROLE APP_USER TO ROLE SYSADMIN_READONLY;
