CREATE USER IF NOT EXISTS TF_SVC DEFAULT_ROLE=SYSADMIN_READONLY MUST_CHANGE_PASSWORD=FALSE DISABLED=FALSE;
ALTER USER TF_SVC SET RSA_PUBLIC_KEY='-----BEGIN PUBLIC KEY----- ... -----END PUBLIC KEY-----';
GRANT ROLE SYSADMIN_READONLY TO USER TF_SVC;
