# 実務ではよく 「本番は SHA 固定」「開発／検証は v1 タグ」 を使い分けます。
# 1. GitHub におけるタグの使い方
# GitHub のタグは、特定のコミットに「ラベル」をつける仕組みです。
# 一般的には次のような用途があります。
# (1) バージョン管理
# git tag v1.0.0 のようにタグを作成し、リリースごとにバージョン番号を付与。
# GitHub では リリース（Releases）機能と連携して、ソースコードのスナップショットやバイナリを配布可能。
# (2) GitHub Actions での参照
# Reusable workflow や Actions を呼び出す際に uses: org/repo/.github/workflows/deploy.yml@v1 のようにタグを指定。
# これにより「安定した状態」を常に呼び出せる。
# (3) CI/CD パイプラインでの安定運用
# v1 タグを更新すれば、呼び出し元はタグ名を変えずに「最新の安定版」を利用できる。
# v1.0.3 のように 固定タグも付ければ、特定バージョンを再現可能。

name: Plan Provenance（供給鎖）
on:
  workflow_run:
    workflows: ["PR Plan（静的解析 + OPA + コスト）"]
    types: [completed]
permissions:
  id-token: write
  contents: write
jobs:
  attest:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: plan-and-json
          path: ./artifacts

      #ダウンロードしたファイル群（./artifacts/*）を **「対象(subject)」**として、SLSA 互換のプロベナンスを生成・署名・保存します。
      #これにより、**「どのコミット／どのワークフロー・環境で、どの入力（アーティファクト）から、どの手順で生成されたか」**を後から検証可能になります（サプライチェーンの信頼性向上）。
      - uses: actions/attest-build-provenance@v1
        with:
          subject-path: "./artifacts/*"

# 何が嬉しいか
# 改ざん検出：Plan 出力（例：plan.binary, plan.json）に出自の証拠を付け、後段（閉域の Apply など）で 検証できる。
# 追跡可能：コミット、ブランチ、トリガーイベント、実行環境などが検証可能なメタデータとして残る。
# ゼロトラスト：アーティファクト受け渡し時に「本当に GitHub Actions がそのコミットから生成した物か？」を暗号的に確認できる。
