name: Deploy NonProd（dev/stg）
on:
  workflow_dispatch:
    inputs:
      env:
        description: "Environment（dev/stg）"
        required: true
        type: choice
        options: [dev, stg]
      stack:
        description: "スタックパス（例: stacks/dev/ap-northeast-1/foundation）"
        required: true
        type: string
permissions:
  contents: read
  id-token: write
  deployments: write
environment:
  name: ${{ inputs.env == 'dev' && 'Dev' || 'Stg' }}
concurrency:
  group: deploy-${{ inputs.env }}-${{ inputs.stack }}
  cancel-in-progress: false
jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with: { terraform_version: "1.8.5" }

      - name: AWS 認証
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ inputs.env == 'dev' && vars.AWS_DEV_APPLY_ROLE_ARN || vars.AWS_STG_APPLY_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: SOPS 復号
        run: |
          echo "${{ secrets.SOPS_AGE_KEY }}" > /tmp/agekey.txt
          export SOPS_AGE_KEY_FILE=/tmp/agekey.txt
          if [ -f "${{ inputs.stack }}/secrets.enc.tfvars" ]; then
            sops -d "${{ inputs.stack }}/secrets.enc.tfvars" > "${{ inputs.stack }}/secrets.dec.tfvars"
          fi

      - name: Terraform Init
        run: terraform -chdir=${{ inputs.stack }} init -backend-config=${{ inputs.stack }}/backend.hcl

      - name: Terraform Plan（再確認）
        run: terraform -chdir=${{ inputs.stack }} plan -var-file=secrets.dec.tfvars -input=false -lock=true -out=tfplan.bin

      - name: Terraform Apply
        run: terraform -chdir=${{ inputs.stack }} apply -input=false -auto-approve tfplan.bin

      - name: 復号ファイル削除
        if: always()
        run: rm -f ${{ inputs.stack }}/secrets.dec.tfvars
